include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - validate
  - test

python-unit-tests:
  only:
    - merge_requests
  image: python:3.10
  script:
    - pip install -U pip
    - pip install -r requirements.txt
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

python-code-quality:
  only:
    - merge_requests
  image: python:3.10
  script:
    - pip install -U pip
    - pip install -r requirements.txt
    - black --check --verbose .
    - flake8
