name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - "bmaden/*"

env:
  TEST_RUNNER_PYTHON_VERSION: "3.10"

jobs:
  unit-test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python ${{env.TEST_RUNNER_PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.TEST_RUNNER_PYTHON_VERSION}}
          cache: pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python -m pytest